"""Generate a tutorial page from Tutorial Hunter results — no LLM API required."""
from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path
from datetime import datetime, timezone

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from tutorial_genesys.models.tutorial_content import TutorialContent, TutorialSection
from tutorial_genesys.agents.illustrator import Illustrator
from tutorial_genesys.delivery.renderer import render_tutorial


def load_hunter_data(db_path: str) -> list[dict]:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT * FROM tutorials ORDER BY final_rank DESC LIMIT 20"
    ).fetchall()
    trends = conn.execute(
        "SELECT * FROM trends ORDER BY velocity DESC LIMIT 10"
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows], [dict(r) for r in trends]


def build_tutorial_from_data(tutorials: list[dict], trends: list[dict]) -> TutorialContent:
    """Build a complete tutorial page showcasing Hunter's discoveries."""

    # Group by topic
    top_repos = [t for t in tutorials if t.get("source") == "github"][:10]
    top_hn = [t for t in tutorials if t.get("source") == "hackernews"][:5]

    # Build markdown
    md_parts = []

    md_parts.append("""## What's Trending in AI Right Now

The AI landscape moves fast. This week, our AI Tutorial Hunter agent scanned GitHub, Hacker News, ArXiv, Medium, and Reddit to find the most valuable learning resources. Here's what's making waves.

> Every tutorial and resource below was discovered, scored, and ranked autonomously by our AI agent pipeline.

""")

    md_parts.append("## Top AI Repositories to Learn From\n\n")
    md_parts.append("These repositories earned the highest quality scores across relevance, freshness, engagement, and depth.\n\n")

    for i, repo in enumerate(top_repos, 1):
        tags = json.loads(repo.get("tags_json", "[]"))
        engagement = json.loads(repo.get("engagement_json", "{}"))
        stars = engagement.get("stars", 0)
        forks = engagement.get("forks", 0)
        score = repo.get("final_rank", 0)

        md_parts.append(f"### {i}. {repo['title']}\n\n")
        md_parts.append(f"**Quality Score: {score:.0f}/100** | ")
        md_parts.append(f"Stars: {stars:,} | Forks: {forks:,}\n\n")
        if repo.get("summary"):
            md_parts.append(f"{repo['summary'][:300]}\n\n")
        md_parts.append(f"[View Repository]({repo['url']})\n\n")

    md_parts.append("## Trending Discussions on Hacker News\n\n")
    md_parts.append("The AI community is buzzing about these topics:\n\n")

    for item in top_hn:
        engagement = json.loads(item.get("engagement_json", "{}"))
        points = engagement.get("points", 0)
        comments = engagement.get("comments", 0)
        md_parts.append(f"- **{item['title'][:80]}** — {points} points, {comments} comments ")
        md_parts.append(f"([read more]({item['url']}))\n")

    md_parts.append("\n## Content Gaps — What Needs Tutorials\n\n")
    md_parts.append("Our gap analysis identified these high-demand topics where quality tutorials are still scarce:\n\n")

    for trend in trends[:5]:
        md_parts.append(f"- **{trend['topic'][:60]}** — velocity: {trend['velocity']:.0f}, volume: {trend['volume']}\n")

    md_parts.append("""
## How This Works

This digest was generated by a two-agent AI pipeline:

1. **AI Tutorial Hunter** scans 6 sources (GitHub, Reddit, Hacker News, YouTube, ArXiv, Medium) for trending AI content
2. **Tutorial Genesys** transforms those discoveries into publication-ready tutorials

```python
# Run the full pipeline
from ai_tutorial_hunter.agents.orchestrator import Orchestrator

async def discover():
    orch = Orchestrator()
    result = await orch.run(max_trends=10)
    print(f"Found {len(result.tutorials)} tutorials")
    print(f"Detected {len(result.gaps)} content gaps")
```

### Try It Yourself

Clone both repositories and run the pipeline locally:

```bash
# Step 1: Run Tutorial Hunter
cd ai-tutorial-hunter
pip install -e .
tutorial-hunter run --max-trends 10

# Step 2: Generate tutorials
cd ../tutorial-genesys
pip install -e .
genesys pipeline --max-tutorials 3
```

## What's Next

Stay tuned for weekly AI tutorial digests covering the latest in:
- Large Language Models and prompt engineering
- AI Agents and autonomous systems
- RAG (Retrieval Augmented Generation)
- Computer Vision and generative AI
- MLOps and model deployment
""")

    markdown_body = "".join(md_parts)

    # Build sections
    sections = []
    import re
    for match in re.finditer(r"^(#{2,3})\s+(.+)$", markdown_body, re.MULTILINE):
        level = len(match.group(1))
        heading = match.group(2).strip()
        sections.append(TutorialSection(
            heading=heading,
            level=level,
            content_markdown="",
            has_code="```" in markdown_body[match.end():match.end()+500],
        ))

    return TutorialContent(
        topic="AI Trends",
        title="This Week in AI: Top Tutorials, Trending Repos, and Content Gaps",
        subtitle="Autonomously discovered and ranked by the AI Tutorial Hunter pipeline",
        difficulty="intermediate",
        category="AI Guides",
        author="The Pulse AI",
        estimated_reading_minutes=12,
        markdown_body=markdown_body,
        sections=sections,
        word_count=len(markdown_body.split()),
        keywords=["AI tutorials", "machine learning", "trending AI", "AI agents", "LLM", "RAG"],
        meta_title="This Week in AI: Top Tutorials & Trending Repos | The Pulse",
        meta_description="AI-curated weekly digest of the best AI tutorials, trending repositories, and content gaps — discovered by autonomous agents.",
    )


def main():
    hunter_db = Path(__file__).parent.parent.parent / "ai-tutorial-hunter" / "tutorial_hunter.db"
    if not hunter_db.exists():
        print(f"Hunter DB not found at {hunter_db}")
        sys.exit(1)

    print("Loading Tutorial Hunter data...")
    tutorials, trends = load_hunter_data(str(hunter_db))
    print(f"  {len(tutorials)} tutorials, {len(trends)} trends")

    print("Building tutorial content...")
    tutorial = build_tutorial_from_data(tutorials, trends)

    print("Generating hero SVG...")
    illustrator = Illustrator()
    tutorial.hero_svg = illustrator.generate_hero_svg(tutorial.title)

    concept_names = ["Trend Detection", "Content Crawling", "Quality Scoring", "Gap Analysis", "Tutorial Generation"]
    concept_diagram = illustrator.generate_concept_diagram(concept_names)

    print("Rendering HTML...")
    html = render_tutorial(tutorial, concept_diagram=concept_diagram)

    # Save output
    output_dir = Path(__file__).parent.parent / "output" / tutorial.slug
    output_dir.mkdir(parents=True, exist_ok=True)

    html_path = output_dir / "index.html"
    html_path.write_text(html, encoding="utf-8")

    svg_path = output_dir / "hero.svg"
    svg_path.write_text(tutorial.hero_svg, encoding="utf-8")

    meta_path = output_dir / "meta.json"
    meta_path.write_text(tutorial.model_dump_json(indent=2, exclude={"hero_svg", "markdown_body"}), encoding="utf-8")

    print(f"\nTutorial generated successfully!")
    print(f"  HTML: {html_path}")
    print(f"  Words: {tutorial.word_count}")
    print(f"  Sections: {len(tutorial.sections)}")

    return str(html_path)


if __name__ == "__main__":
    main()
